sftp:
  - hostname: '127.0.0.1'
    port: 22
    username: ansible
    password: '#!Sala1234'
    remote_directory: /opt/dokuwiki/config/dokuwiki/data/pages/
    local_directory: data/wikipages

whoosh_index_dir: "whoosh_doc_index"
