sftp:
  - hostname: '127.0.0.1'
    port: 22
    username: ansible
    private_key: ~/.ssh/id_ed25519
    remote_directory: /opt/data/
    local_directory: data/wikipages

local_file:
  - path: '/tmp/sample.txt'
    title: 'sample'

web:
  - url: 'https://example.com'

#TBD
rss: []
  #- url: ''

whoosh_index_dir: "whoosh_doc_index"
