sftp:
  - hostname: '127.0.0.1'
    port: 22
    username: ansible
    private_key: ~/.ssh/id_ed25519
    remote_directory: /opt/data/
    local_directory: data/wikipages

local_file:
  - path: '/tmp/sample.txt'
    title: 'sample'

web:
  - url: 'https://example.com'

#TBD
rss: []
  #- url: ''

whoosh_index:
  dir: "whoosh_doc_index"
  schema: # 'Schema(id=ID(stored=True,unique=True),date=DATETIME(stored=True), title=KEYWORD(stored=True), path=TEXT(stored=True), content=TEXT(stored=True))'
    id:
      type: ID
      unique: true
      stored: true
    title:
      type: KEYWORD
      unique: false
      stored: true
    path:
      type: TEXT
      unique: false
      stored: true
    content:
      type: TEXT
      unique: false
      stored: true
