sftp:
  - hostname: '127.0.0.1'
    port: 22
    username: ansible
    private_key: ~/.ssh/id_ed25519
    remote_directory: /opt/data/
    local_directory: data/wikipages

local_file:
  - path: '/tmp/sample.txt'
    title: 'sample'

web:
  - url: 'https://example.com'

rss: []
  #- url: ''

whoosh_index:
  dir: "whoosh_doc_index"
  # Fields 'ID(id)' 'TEXT(content)' are always added to schema
  schema:
    title:
      type: KEYWORD
      unique: false
      stored: true
    path:
      type: TEXT
      unique: false
      stored: true
    summary:
      type: TEXT
      unique: false
      stored: true
    url:
      type: TEXT
      unique: false
      stored: true
    datatype:
      type: TEXT
      unique: false
      stored: true
    date:
      type: DATETIME
      unique: false
      stored: true

